# Generated by Django 5.2.7 on 2026-02-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reset_subscriber_conflict'),
        ('blog', '0003_create_subscriber_table'),
    ]

    operations = [
    ]
